"""
Django settings for dcrm project.

Generated by 'django-admin startproject' using Django 4.2.11.

Este archivo concentra configuración global del proyecto: apps instaladas,
middleware, base de datos, seguridad, sesiones, archivos estáticos y URLs.
"""

import os
from pathlib import Path


BASE_DIR = Path(__file__).resolve().parent.parent

# Mantener DEBUG activo en local evita forzar HTTPS durante el desarrollo.
DEBUG = True

# En desarrollo permitimos localhost; en producción deben declararse hosts reales.
ALLOWED_HOSTS = ['127.0.0.1', 'localhost'] if DEBUG else []

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-wrd@k5c63l-25ln)85jwma^uf$he_n077de(m!-(rhiu5#*d+q'


INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # WebsiteConfig.ready() registra las señales usadas por el patrón Observer.
    'website.apps.WebsiteConfig',
]

# El orden del middleware es importante: sesión y autenticación deben cargar antes de mensajes.
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'dcrm.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'dcrm.wsgi.application'

# En Docker la base de datos vive en el servicio "db"; en local se mantiene
# localhost como respaldo para no romper el flujo de desarrollo existente.
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.environ.get('DJANGO_DB_NAME', 'clientes'),
        'USER': os.environ.get('DJANGO_DB_USER', 'root'),
        'PASSWORD': os.environ.get('DJANGO_DB_PASSWORD', ''),
        'HOST': os.environ.get('DJANGO_DB_HOST', 'localhost'),
        'PORT': os.environ.get('DJANGO_DB_PORT', '3306'),
    }
}


AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Localización base del proyecto. La interfaz muestra textos en español desde
# templates, formularios y mensajes, aunque el idioma técnico de Django siga en-us.
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


STATIC_URL = 'static/'
STATICFILES_DIRS = [
    # Los archivos estáticos viven dentro de templates/static en este proyecto.
    os.path.join(BASE_DIR, 'website', 'templates', 'static'),
]

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# En HTTP local no se pueden usar cookies seguras, porque el navegador no las
# devuelve y la sesión aparenta perderse justo después del login.
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG
# Si el token CSRF falla, mostramos un mensaje claro en la app en vez del 403 técnico.
CSRF_FAILURE_VIEW = 'website.views.csrf_failure'
SECURE_SSL_REDIRECT = not DEBUG
SECURE_HSTS_SECONDS = 31536000 if not DEBUG else 0
SECURE_HSTS_INCLUDE_SUBDOMAINS = not DEBUG
SECURE_HSTS_PRELOAD = not DEBUG

SESSION_COOKIE_AGE = 1209600
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SESSION_SAVE_EVERY_REQUEST = True

# Capas de seguridad del entregable:
# 1. Autenticación/autorización por roles en vistas protegidas.
# 2. CSRF activo en formularios y vista personalizada de error.
# 3. Cookies de sesión/CSRF endurecidas contra lectura por scripts y envío cross-site.
# 4. Cabeceras de navegador para reducir clickjacking, MIME sniffing y fuga de referer.
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_HTTPONLY = True
CSRF_COOKIE_SAMESITE = 'Lax'
X_FRAME_OPTIONS = 'DENY'
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_REFERRER_POLICY = 'same-origin'
SECURE_CROSS_ORIGIN_OPENER_POLICY = 'same-origin'

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'home'
