"""
Django settings for dcrm project.

Generated by 'django-admin startproject' using Django 4.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os # llamar para que funcione las rutas

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-wrd@k5c63l-25ln)85jwma^uf$he_n077de(m!-(rhiu5#*d+q'



ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'website.apps.WebsiteConfig',# por defecto no se crea, hay que crearla con el comando "python manage.py startapp website"
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'dcrm.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'dcrm.wsgi.application'

#seguridad de la base de datos
# Asegurar que las credenciales de la base de datos no estén expuestas en el código fuente, por ejemplo, utilizando variables de entorno o un archivo de configuración separado.

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases
# Por defecto se usa sqlite3, pero se puede cambiar por otro motor de base de datos como MySQL, PostgreSQL, etc.
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql', # Cambiar por el motor de base de datos que se quiera usar, por ejemplo 'django.db.backends.postgresql' para PostgreSQL
        'NAME': 'clientes', # Cambiar por el nombre de la base de datos que se quiera usar
        'USER': 'root',
        'PASSWORD': '',
        'HOST': 'localhost',
        'PORT': '3306',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'website', 'templates', 'static'),
] # Agregar esta línea para indicar la carpeta donde se encuentran los archivos estáticos

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'



#Capas de seguridad
#Seguridad de la red
# SECURE_SSL_REDIRECT = True # Redirigir todas las solicitudes a HTTPS
SESSION_COOKIE_SECURE = True # Asegurar que las cookies de sesión solo se enví
CSRF_COOKIE_SECURE = True # Asegurar que las cookies CSRF solo se envíen a través de HTTPS
SECURE_HSTS_SECONDS = 31536000 # Habilitar HTTP Strict Transport Security (
SECURE_HSTS_INCLUDE_SUBDOMAINS = True # Incluir subdominios en HSTS
COOKIE_SECURE = True # Asegurar que las cookies solo se envíen a través de HTTPS
SECURE_HSTS_PRELOAD = True # Habilitar la precarga de HSTS
#expiracion de sessiones

SESSION_COOKIE_AGE = 1209600 # Establecer la duración de las cookies de sesión (en segundos)
SESSION_EXPIRE_AT_BROWSER_CLOSE = True # Expirar las sesiones al cerrar el navegador
#cierra sesion si no hay eventos dentro del sitio
SESSION_SAVE_EVERY_REQUEST = True # Guardar la sesión en cada solicitud para actualizar la expiración


#Seguridad en la aplicación

SECURE_CONTENT_TYPE_NOSNIFF = True # Evitar que el navegador intente adivinar el tipo de contenido
SECURE_BROWSER_XSS_FILTER = True # Habilitar el filtro XSS del navegador
'django.middleware.security.SecurityMiddleware', # Agregar esta línea en MIDDLEWARE para habilitar la seguridad de la aplicación

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

#Seguridad de el servidor

# ALLOWED_HOSTS = ['localhost', '127.0.0.1'] # Agregar los hosts permitidos para evitar ataques de host header

