# Generated by Django 5.2.8 on 2026-05-15 21:46

from django.db import migrations, models


# Migración inicial:
# crea la tabla de clientes usada por el modelo Record.
# Las migraciones son historial de esquema; no contienen lógica de negocio.
class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        # Tabla principal de clientes/records.
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('zip_code', models.CharField(max_length=10)),
            ],
        ),
    ]
